openapi: 3.0.0
info:
  title: SMBMS - Bill API
  version: 1.0.11
  description: RESTful API for managing bills and providers in SMBMS.
  contact:
    email: Jun.Amane@zzy040330.moe
  license:
    name: MIT
    url: https://github.com/Jun-Amane/smbms
  termsOfService:
    url: https://github.com/Jun-Amane/smbms

paths:
  /api/bill:
    get:
      summary: Query bills
      security:
        - bearerAuth: []
      parameters:
        - name: queryProductName
          in: query
          description: Product Name
          required: false
          explode: true
          schema:
            type: string
        - name: queryProviderId
          in: query
          description: Provider Id
          required: false
          explode: true
          schema:
            type: integer
        - name: queryIsPaid
          in: query
          description: Is Paid or not
          required: false
          explode: true
          schema:
            type: string
            enum:
              - true
              - false
        - name: pageIndex
          in: query
          description: Page Index
          required: false
          explode: true
          schema:
            type: integer
        - name: pageSize
          in: query
          description: Page Size
          required: false
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of bills
          content:
            application/json:
              schema:
                type: object
                required:
                  - pageSize
                  - totalPages
                  - curPage
                  - totalItems
                  - bills
                properties:
                  pageSize:
                    type: integer
                    example: 15
                  totalPages:
                    type: integer
                    example: 3
                  curPage:
                    type: integer
                    example: 2
                  totalItems:
                    type: integer
                    example: 42
                  bills:
                    type: array
                    items:
                      $ref: '#/components/schemas/Bill'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Add a new bill
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: Bill Entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bill'
      responses:
        '201':
          description: Bill added successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/bill/{id}:
    get:
      summary: Get bill by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Bill ID
          required: true
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: The bill information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
        '404':
          description: Bill not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Modify bill details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Bill ID
          required: true
          explode: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bill'
      responses:
        '204':
          description: Bill modified successfully
        '404':
          description: Bill not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a bill
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Bill ID
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: Bill deleted successfully
        '404':
          description: Bill not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/bill/providerlist:
    get:
      summary: Get list of providers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Bill:
      type: object
      required:
        - id
        - code
        - productName
        - productDescription
        - productCount
        - totalPrice
        - isPaid
        - providerId
      properties:
        id:
          type: integer
          description: Bill identifier
          example: 1
        code:
          type: string
          description: Bill code
          example: BILL2016_001
        productName:
          type: string
          description: Product name
          example: 电话微波炉【暂定】
        productDescription:
          type: string
          description: Product description
          example: 日用品
        productUnit:
          type: string
          description: Product unit
          example: 个
        productCount:
          type: number
          format: double
          description: Product count
          example: 1
        totalPrice:
          type: number
          format: double
          description: Total price
          example: 571802
        isPaid:
          type: boolean
          description: Payment status
          example: true
        providerId:
          type: integer
          description: Provider ID
          example: 1

    Provider:
      type: object
      required:
        - id
        - code
        - name
        - description
        - contact
        - phone
        - address
        - fax
      properties:
        id:
          type: integer
          description: Provider identifier
          example: 1
        code:
          type: string
          description: Provider code
          example: JP_MRK001
        name:
          type: string
          description: Provider name
          example: 未来道具研究所
        description:
          type: string
          description: Provider description
          example: 长期合作伙伴
        contact:
          type: string
          description: Provider contact person
          example: Hououin Kyoma
        phone:
          type: string
          description: Provider phone number
          example: 12345678901
        address:
          type: string
          description: Provider address
          example: 藏前桥路交叉路口小巷
        fax:
          type: string
          description: Provider fax number
          example: 0532-12345678

    ErrorResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          example: 500
        message:
          type: string
          example: internal error
